#!/bin/bash
#######################################################################################################
#   This file can be used to run Mask RCNN using the cloned detectron library
#   
#   Author: Sid Pethe
#
#######################################################################################################
configFile=~/detectronRoot/Detectron/configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml
outputDirectory=~/detectronRoot/runFolder/kitti_results/
inputExtension=png
outputExtension=png
weightsFilePath=~/DetectronModelWts/e2e_mask_rcnn_R-101-FPN_2x.pkl
inputDirectory=~/detectronRoot/input/
detectionThreshold=0.7
JunVis=false

if $JunVis; then
    python2 ~/detectronRoot/Detectron/tools/infer_simple.py --cfg $configFile --output-dir $outputDirectory  --output-ext $outputExtension  --image-ext $inputExtension --Jun-vis  --wts $weightsFilePath --thresh $detectionThreshold  $inputDirectory
else
    python2 ~/detectronRoot/Detectron/tools/infer_simple.py --cfg $configFile --output-dir $outputDirectory  --output-ext $outputExtension  --image-ext $inputExtension  --wts $weightsFilePath --thresh $detectionThreshold  $inputDirectory
fi
